version: '2'

services:
  front:
    image: dydx/alpine-nginx-phpfpm
    ports:
      - "8080:80"
    volumes:
      - .:/var/www:delegated
      - ./default.conf:/etc/nginx/sites-enabled/default
    links:
      - mysql:mysql

  mysql:
    image: dydx/alpine-mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql