<?php
/**
 * @file
 * Code for the portico_wufoo feature.
 */

include_once 'portico_wufoo.features.inc';


function portico_wufoo_subtype_options_alter(&$options, $form_state) {
  switch($form_state['bundle']) {
    case 'wufoo':
      $options = array(
        'opportunities_to_serve' => t('Opportunities to Serve'),
        'tell_the_story' => t('Tell The Story'),
        'interested_in_leadership' => t('Interested In Leadership'),
        'ministry_support' => t('Ministry Support'),
        'interested_in_connectionmembership_at_portico' => t('Interested in Connection/Membership at Portico'),
      );
      break;
  }
}


function portico_wufoo_entity_view_alter(&$build, $type) {
  if ($type !== 'node' || $build['#bundle'] !== 'wufoo') {
    return FALSE;
  }

  $subtype = field_get_items('node', $build['#node'], 'field_subtype', NULL);
  $subtype = reset($subtype);

  $function_call = empty($subtype) ? '' : 'portico_wufoo_retrieve_wufoo_' . $subtype['value'];

  if (!empty($function_call) && function_exists($function_call)) {
    $output = $function_call();
  } else {
    $output = '';
  }

  $build['form'] = array(
    '#markup' => $output,
    '#prefix' => '<div class=\'wufoo-form-wrapper\'>',
    '#suffix' => '</div>'
  );

}

/**
 * [portico_wufoo_retrieve_wufoo_opportunities_to_serve description]
 * @return [type] [description]
 */
function portico_wufoo_retrieve_wufoo_opportunities_to_serve() {

  $output = <<<EOF
  <div id="wufoo-z6k3rp11mq0ldk">
  Fill out my <a href="https://porticoarlington.wufoo.com/forms/z6k3rp11mq0ldk">online form</a>.
  </div>
  <script type="text/javascript">var z6k3rp11mq0ldk;(function(d, t) {
  var s = d.createElement(t), options = {
  'userName':'porticoarlington',
  'formHash':'z6k3rp11mq0ldk',
  'autoResize':true,
  'height':'1188',
  'async':true,
  'host':'wufoo.com',
  'header':'show',
  'ssl':true};
  s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'www.wufoo.com/scripts/embed/form.js';
  s.onload = s.onreadystatechange = function() {
  var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
  try { z6k3rp11mq0ldk = new WufooForm();z6k3rp11mq0ldk.initialize(options);z6k3rp11mq0ldk.display(); } catch (e) {}};
  var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
  })(document, 'script');</script>
EOF;

  return $output;
}

/**
 * [portico_wufoo_retrieve_wufoo_tell_the_story description]
 * @return [type] [description]
 */
function portico_wufoo_retrieve_wufoo_tell_the_story() {
  $output = <<<EOF
  <div id="wufoo-mqk22v01auxcsw">
  Fill out my <a href="https://porticoarlington.wufoo.com/forms/mqk22v01auxcsw">online form</a>.
  </div>
  <script type="text/javascript">var mqk22v01auxcsw;(function(d, t) {
  var s = d.createElement(t), options = {
  'userName':'porticoarlington',
  'formHash':'mqk22v01auxcsw',
  'autoResize':true,
  'height':'755',
  'async':true,
  'host':'wufoo.com',
  'header':'show',
  'ssl':true};
  s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'www.wufoo.com/scripts/embed/form.js';
  s.onload = s.onreadystatechange = function() {
  var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
  try { mqk22v01auxcsw = new WufooForm();mqk22v01auxcsw.initialize(options);mqk22v01auxcsw.display(); } catch (e) {}};
  var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
  })(document, 'script');</script>

EOF;

  return $output;
}

/**
 * [portico_wufoo_retrieve_wufoo_interested_in_leadership description]
 * @return [type] [description]
 */
function portico_wufoo_retrieve_wufoo_interested_in_leadership() {
  $output = <<<EOF
  <div id="wufoo-s1trq3731bbpyo6">
  Fill out my <a href="https://porticoarlington.wufoo.com/forms/s1trq3731bbpyo6">online form</a>.
  </div>
  <script type="text/javascript">var s1trq3731bbpyo6;(function(d, t) {
  var s = d.createElement(t), options = {
  'userName':'porticoarlington',
  'formHash':'s1trq3731bbpyo6',
  'autoResize':true,
  'height':'1328',
  'async':true,
  'host':'wufoo.com',
  'header':'show',
  'ssl':true};
  s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'www.wufoo.com/scripts/embed/form.js';
  s.onload = s.onreadystatechange = function() {
  var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
  try { s1trq3731bbpyo6 = new WufooForm();s1trq3731bbpyo6.initialize(options);s1trq3731bbpyo6.display(); } catch (e) {}};
  var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
  })(document, 'script');</script>

EOF;

  return $output;
}

/**
 * [portico_wufoo_retrieve_wufoo_ministry_support description]
 * @return [type] [description]
 */
function portico_wufoo_retrieve_wufoo_ministry_support() {
  $output = <<<EOF
  <div id="wufoo-s1gcjday1d7j8ni">
  Fill out my <a href="https://porticoarlington.wufoo.com/forms/s1gcjday1d7j8ni">online form</a>.
  </div>
  <script type="text/javascript">var s1gcjday1d7j8ni;(function(d, t) {
  var s = d.createElement(t), options = {
  'userName':'porticoarlington',
  'formHash':'s1gcjday1d7j8ni',
  'autoResize':true,
  'height':'1318',
  'async':true,
  'host':'wufoo.com',
  'header':'show',
  'ssl':true};
  s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'www.wufoo.com/scripts/embed/form.js';
  s.onload = s.onreadystatechange = function() {
  var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
  try { s1gcjday1d7j8ni = new WufooForm();s1gcjday1d7j8ni.initialize(options);s1gcjday1d7j8ni.display(); } catch (e) {}};
  var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
  })(document, 'script');</script>

EOF;

  return $output;
}

/**
 * [portico_wufoo_retrieve_wufoo_interested_in_connectionmembership_at_portico description]
 * @return [type] [description]
 */
function portico_wufoo_retrieve_wufoo_interested_in_connectionmembership_at_portico() {
  $output = <<<EOF
  <div id="wufoo-snhw5j00lzfo29">
  Fill out my <a href="https://porticoarlington.wufoo.com/forms/snhw5j00lzfo29">online form</a>.
  </div>
  <script type="text/javascript">var snhw5j00lzfo29;(function(d, t) {
  var s = d.createElement(t), options = {
  'userName':'porticoarlington',
  'formHash':'snhw5j00lzfo29',
  'autoResize':true,
  'height':'1333',
  'async':true,
  'host':'wufoo.com',
  'header':'show',
  'ssl':true};
  s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'www.wufoo.com/scripts/embed/form.js';
  s.onload = s.onreadystatechange = function() {
  var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
  try { snhw5j00lzfo29 = new WufooForm();snhw5j00lzfo29.initialize(options);snhw5j00lzfo29.display(); } catch (e) {}};
  var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
  })(document, 'script');</script>

EOF;

  return $output;
}
