<?php
/**
 * @file
 * Code for the Portico Structure feature.
 */

include_once 'portico_structure.features.inc';
include_once 'includes/portico_structure.block.inc';
include_once 'includes/portico_structure.admin.inc';

function portico_structure_admin_paths_alter(&$paths) {
  // Treat all user pages as administrative.
  $paths ['user']   = TRUE;
  $paths ['user/*'] = TRUE;
}

/**
 * Implements hook_menu().
 */
function portico_structure_menu() {

  $items['admin/content/portico'] = array(
    'title' => t('Portico'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('portico_config'),
    'access arguments' => array('administer configuration'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}