<?php
/**
 * @file
 * Code for the Portico Now feature.
 */

include_once 'portico_now.features.inc';

/**
 * [portico_blog_subtype_options_alter description]
 * @param  [type] &$options   [description]
 * @param  [type] $form_state [description]
 * @return [type]             [description]
 */
function portico_now_subtype_options_alter(&$options, $form_state) {
  if ($form_state['bundle'] == 'page') {
    $options['portico_now'] = t('Portico Now Landing Page');
  }
}

/**
 * Implements hook_entity_view_alter
 * @param  [type] &$build [description]
 * @param  [type] $type   [description]
 * @return [type]         [description]
 */
function portico_now_entity_view_alter(&$build, $type) {
  switch ($type) {
    case 'node':
      switch ($build['#bundle']) {
        case 'page':
          if ($subtype = field_get_items('node', $build['#node'], 'field_subtype')) {
            $subtype = reset($subtype);
            if ($subtype['value'] == 'portico_now') {
              portico_now_aggregate_nodes($build);
            }
          }
          break;
      }
      break;
  }
}

/**
 * [portico_now_aggregate_nodes description]
 * @param  [type] $build [description]
 * @return [type]        [description]
 */
function portico_now_aggregate_nodes(&$build) {
  $nids = variable_get('portico_structure_portico_now_weights');

  if (empty($nids)) {
    return $build;
  }

  $keys = array_keys($nids);
  $loaded = entity_load('node', $keys);
  $viewed = entity_view('node', $loaded, 'teaser');

  $build['pnow-nodes'] = $viewed['node'];

}

/**
 * Implements hook_preprocess_field().
 */
function portico_now_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] == 'field_portico_now_category') {
    $variables['classes_array'][] = 'term-' . drupal_html_class($variables['items'][0]['#markup']);
  }
}

/**
 * Implements hook_preprocess_page().
 */
function portico_now_preprocess_page(&$vars) {
  $pnow = portico_structure_get_subtype('portico_now');
  if (empty($pnow) || empty($vars['node'])) {
    return;
  }

  if ($pnow->nid !== $vars['node']->nid) {
    return;
  }

  $sidebar = array();
  try {
    $page = $vars['page']['content']['system_main']['nodes'][$pnow->nid];
    if (!empty($page['pnow-nodes'])) {
      $vars['page']['sidebar_first']['scrollsidebar'] = portico_now_get_pnow_titles($page['pnow-nodes']);
    }

  }
  catch (Exception $e) {
  }

}

/**
 * PNOW title aggregator.
 */
function portico_now_get_pnow_titles($nodes) {
  $output = $items = array();
  foreach ($nodes as $node) {
    if (!is_array($node)) {
      continue;
    }
    
    $title = explode('|', $node['#node']->title);

    $items[] = l(trim($title[0]), current_path(), array(
      'fragment' => 'node-' . $node['#node']->nid,
    ));
  }

  $output['#theme'] = 'item_list';
  $output['#items'] = $items;
  $output['#attributes'] = array('class' => array('jump-list'));
  return $output;
}
